import Head from 'next/head';

import Dice from '../pages/comps/dice';

import styles from '../styles/Home.module.css';



 



export default function Home() {
  return (




    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dice/>
      <button>Click me!</button>
      <br></br>
      button that does something. 
      <br></br>
      2 characters? 2 versions of stories?

      <main >
       

        I will make a component that is a random dice roller that will appear on each page....or a log section to keep track of notes.
      <br></br>
        I will put an introduction/rules section here!
        <br></br>
        I will put a button here!
        <br></br>
         
        <button >Click me!</button>
       
      </main>
    {/*Short paragraphs that introduce you to instructions, needed items and story */}
    {/*At bottom of every box will be buttons that give multiple selections that take person to another page */}
    {/*onload/onclick overlay screen effect?/}
    {/*stat tracker?? HP bar or something?*/}
    {/*small pictures of people to overlay or pop up? */}
    {/*CONGRATS with start over button */}

      <footer>
       DA FOOT
       <br></br>
       Restart button? Return home button?
       <button>Click me!</button>
      </footer>
    </div>
  )
}
